# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(max_length=10000, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '被评论文章',
                'verbose_name_plural': '被评论文章',
            },
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='名称')),
                ('content', models.CharField(max_length=1024000, verbose_name='内容')),
                ('li', models.CharField(max_length=100, verbose_name='编号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '文章名称',
                'verbose_name_plural': '文章名称',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('isban', models.BooleanField(default=False, verbose_name='禁用')),
                ('isdelete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.content'),
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
    ]
